services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-revline}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-revline}
      POSTGRES_DB: ${POSTGRES_DB:-revline}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-revline} -d ${POSTGRES_DB:-revline}"]
      interval: 3s
      timeout: 3s
      retries: 40

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 40

  api:
    build:
      context: ../api             # ← context is the api folder
      dockerfile: Dockerfile.dev  # ← path is relative to context
    env_file: ../.env
    working_dir: /app
    volumes:
      - ../api:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: >
      sh -c "uvicorn app.main:app --host ${API_HOST:-0.0.0.0}
      --port ${API_PORT:-8000} --reload"

  # Vite dev server for local DX
  web:
    build:
      context: ../frontend         # ← context is the frontend folder
      dockerfile: Dockerfile.dev   # ← path is relative to context
    env_file: ../.env
    working_dir: /app
    volumes:
      - ../frontend:/app
      - web_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - api
    environment:
      - IN_DOCKER=1
      - VITE_API_BASE=/api/v1
    command: >
      sh -c "npm ci || npm install &&
      npm run dev -- --host 0.0.0.0 --port 5173"

  frontend-prod:
    image: infra-frontend-prod
    build:
      context: ../frontend
      dockerfile: Dockerfile.prod
    ports:
      - "8080:80"
    depends_on:
      - api
    volumes:
      - ../infra/nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
      - API_URL=http://api:8000


volumes:
  pg_data:
  web_node_modules:
